version: '3'

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    environment:
      HEALTHCHECK_URL: "http://localhost/health"
    user: "1000:1000"
    volumes:
      - type: volume
        source: jellyfin_config
        target: /config
      - type: volume
        source: jellyfin_cache
        target: /cache
      - type: bind
        source: /mnt/media/MediaFiles
        target: /media
    networks:
      macvlan_containers:
        ipv4_address: 192.168.0.203
    restart: always
  qbittorent:
    container_name: qbittorent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      PUID: "1000"
      GUID: "1000"
      TZ: "Asia/Manila"
      WEBUI_PORT: "80"
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - /mnt/media/MediaFiles:/downloads
      - type: volume
        source: qbittorent_config
        target: /config
    networks:
      macvlan_containers:
        ipv4_address: 192.168.0.202
    restart: always
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    volumes:
      - type: volume
        source: portainer_data
        target: /data
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      macvlan_containers:
        ipv4_address: 192.168.0.201
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always
  pihole:
    container_name: pihole
    image: pihole/pihole
    environment:
      TZ: "Asia/Manila"
      WEBPASSWORD: "password"
      SERVERIP: "192.168.0.200"
    volumes:
      - type: volume
        source: pihole_app
        target: /etc/pihole
      - type: volume
        source: dns_config
        target: /etc/dnsmasq.d
    networks:
      macvlan_containers:
        ipv4_address: 192.168.0.200
    restart: always

networks:
  macvlan_containers:
    name: macvlan_containers
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
    
volumes:
  pihole_app:
    name: pihole_app
  dns_config:
    name: dns_config
  portainer_data:
    name: portainer_data
  qbittorent_config:
    name: qbittorent_config
  jellyfin_config:
    name: jellyfin_config
  jellyfin_cache:
    name: jellyfin_cache
